// {
//   "matchScore": 88,
//   "technicalQuestions": [
//     "question",
//     "Explain the flow of data in a MERN stack application, specifically how a React frontend communicates with a Node/Express backend to update MongoDB.",
//     "intention",
//     "To assess the candidate's understanding of full-stack architecture and integration.",
//     "answer",
//     "The React frontend sends an HTTP request (using fetch or Axios) to a specific Express route. The Express server processes the request, performs business logic, and uses Mongoose to interact with MongoDB. The database returns the result to Node, which then sends a JSON response back to React to update the UI state.",        
//     "question",
//     "In your Resume Intelligence project, how did you implement JWT for authentication and why is it preferred over session-based authentication?",
//     "intention",
//     "To evaluate knowledge of web security and stateless authentication.",
//     "answer",
//     "JWT was implemented by generating a token upon login and sending it to the client. The client includes this token in the Authorization header for subsequent requests. It is preferred because it is stateless, making the backend more scalable as the server doesn't need to store session data in memory.",
//     "question",
//     "What is the difference between 'find()' and 'findOne()' in Mongoose, and how do you handle errors in asynchronous database calls?",
//     "intention",
//     "To check proficiency with MongoDB/Mongoose and asynchronous JavaScript.",
//     "answer",
//     "find() returns an array of all matching documents, while findOne() returns the first document that matches the criteria. Asynchronous errors are handled using try-catch blocks with async/await or .catch() blocks in promises to prevent server crashes.",
//     "question",
//     "How do you manage state in a React application, and have you used any hooks like useContext or useReducer?",
//     "intention",
//     "To gauge depth of React knowledge beyond basic component rendering.",
//     "answer",
//     "State is managed using the useState hook for local component state. For global state or complex logic, useContext or useReducer can be used to avoid prop drilling. I focus on keeping state as local as possible to optimize performance.",
//     "question",
//     "Explain the concept of Middleware in Express.js and provide an example from your Banking Transaction System.",
//     "intention",
//     "To verify understanding of the Express.js request-response cycle.",
//     "answer",
//     "Middleware functions have access to the request and response objects and can execute code or terminate the request. In my banking system, I used middleware for validating user input and checking if a user has sufficient balance before processing a withdrawal."
//   ],
//   "behavioralQuestions": [
//     "question",
//     "Describe a challenging bug you faced in your Banking Transaction System and the steps you took to resolve it.",
//     "intention",
//     "To evaluate problem-solving skills and debugging methodology.",
//     "answer",
//     "I encountered an issue where concurrent transactions led to incorrect balance updates. I researched and implemented Mongoose transactions and atomic updates to ensure data integrity, demonstrating my ability to handle complex logic and data consistency.",
//     "question",
//     "How do you stay updated with the rapidly changing MERN stack ecosystem while pursuing your MCA?",        
//     "intention",
//     "To assess passion for continuous learning and time management.",
//     "answer",
//     "I follow technical blogs, participate in GitHub open-source discussions, and dedicate time each weekend to self-learning platforms. I balance this with my MCA coursework by applying academic concepts like DBMS and OS to my web development projects.",
//     "question",
//     "Tell me about a time you had to explain a technical concept to someone with a non-technical background.",
//     "intention",
//     "To evaluate communication skills and the ability to simplify complex ideas.",
//     "answer",
//     "During my Virtual Classroom project, I explained the 'role-based access' feature to a peer by comparing it to a physical school where only teachers have keys to the staff room while students only have access to classrooms.",
//     "question",
//     "What motivated you to transition from Django/Python to the MERN stack for your recent projects?",        
//     "intention",
//     "To understand the candidate's career direction and technology preferences.",
//     "answer",
//     "While I appreciate Django's 'batteries-included' approach, I found the MERN stack's JavaScript-everywhere philosophy more flexible for building highly interactive, real-time single-page applications, which aligns with my interest in modern frontend frameworks.",
//     "question",
//     "Where do you see your technical skills evolving in the next two years?",
//     "intention",
//     "To assess long-term goals and alignment with the company's growth.",
//     "answer",
//     "I aim to master advanced React patterns, explore cloud-native deployment using AWS, and contribute to large-scale scalable architectures, eventually moving into a Senior Full-Stack Developer role."
//   ],
//   "skillGaps": [
//     "skill",
//     "Advanced State Management (Redux/Zustand)",
//     "severity",
//     "medium",
//     "skill",
//     "Cloud Deployment & DevOps (Docker/AWS)",
//     "severity",
//     "high",
//     "skill",
//     "Unit & Integration Testing (Jest/Mocha)",
//     "severity",
//     "medium",
//     "skill",
//     "TypeScript Integration",
//     "severity",
//     "low"
//   ],
//   "preparationPlan": [
//     "day",
//     1,
//     "focus",
//     "JavaScript Fundamentals & Node.js Core",
//     "tasks",
//     "Review Event Loop, Closures, and Hoisting.",
//     "Practice building a custom middleware in Express.",
//     "Refactor a project to use Async/Await properly."
//   ],
//   "preparationPlan": [
//     "day",
//     2,
//     "focus",
//     "React Deep Dive",
//     "tasks",
//     "Study React Hooks (useEffect, useMemo, useCallback).",
//     "Build a small project using Context API for state management.",
//     "Practice creating reusable UI components with Bootstrap."
//   ],
//   "preparationPlan": [
//     "day",
//     3,
//     "focus",
//     "Database & API Security",
//     "tasks",
//     "Review MongoDB Aggregation pipelines.",
//     "Implement Refresh Tokens in a JWT flow.",
//     "Study SQL vs NoSQL performance trade-offs."
//   ],
//   "preparationPlan": [
//     "day",
//     4,
//     "focus",
//     "System Design & Testing",
//     "tasks",
//     "Learn basic Unit Testing with Jest for Node.js APIs.",
//     "Sketch the architecture of the Banking System on a whiteboard.",
//     "Research REST API best practices (versioning, status codes)."
//   ],
//   "preparationPlan": [
//     "day",
//     5,
//     "focus",
//     "Mock Interviews & Soft Skills",
//     "tasks",
//     "Record a 2-minute walkthrough of the Resume Intelligence project.",
//     "Practice STAR method for behavioral questions.",
//     "Review common HR interview questions."
//   ]
// }







// {
//   "matchScore": 92,
//   "technicalQuestions": [
//     "question", "Explain the middleware pattern in Express.js and how you used it for authentication in your Resume Intelligence project.",
//     "intention", "To evaluate the candidate's understanding of Node.js request-response cycles and security implementation.",
//     "answer", "Middleware functions have access to the request and response objects. In my project, I used custom middleware to verify JWT tokens before allowing access to protected routes, ensuring only authenticated users could manage resume data.",
//     "question", "How do you handle concurrent transactions in your Banking Transaction System to prevent data inconsistency?",
//     "intention", "To assess knowledge of database integrity and transaction management in MongoDB.",
//     "answer", "I utilize Mongoose sessions and transactions to ensure atomicity. This ensures that if a withdrawal fails, the balance isn't updated, maintaining ACID properties even in a NoSQL environment.",
//     "question", "What is the difference between Virtual DOM and Real DOM in React.js?",     
//     "intention", "To check fundamental understanding of React's rendering optimization.",   
//     "answer", "The Virtual DOM is a lightweight copy of the Real DOM. React uses it to identify specific changes via a 'diffing' algorithm and updates only those parts in the Real DOM, which significantly improves performance.",
//     "question", "Compare your experience using Django with MySQL versus Node.js with MongoDB.",
//     "intention", "To understand the candidate's ability to choose the right tool for a specific use case.",
//     "answer", "Django provides a robust ORM and built-in admin panel suitable for structured data like Employee Management. Node.js with MongoDB offers more flexibility and scalability for JSON-heavy applications like the Banking system.",
//     "question", "How do you manage state in a React application?",
//     "intention", "To gauge proficiency in frontend data flow.",
//     "answer", "I use the useState hook for local component state and useEffect for side effects. For larger applications, I would look into the Context API or Redux to manage global state across multiple components."
//   ],
//   "behavioralQuestions": [
//     "question", "Describe a challenging bug you encountered in your Virtual Classroom System and how you resolved it.",
//     "intention", "To evaluate problem-solving skills and persistence.",
//     "answer", "I faced an issue with role-based access where students could access faculty pages. I debugged the Django view decorators and corrected the logic in the database models to strictly enforce permissions.",
//     "question", "As an MCA student, how do you stay updated with rapidly changing web technologies?",
//     "intention", "To assess the candidate's passion for continuous learning.",
//     "answer", "I follow tech blogs, participate in GitHub open-source discussions, and dedicate time to self-learning platforms to master stacks like MERN beyond my university curriculum.",
//     "question", "Tell me about a time you had to explain a technical concept to a non-technical person.",
//     "intention", "To evaluate communication skills.",
//     "answer", "While working on the Employee Management System, I explained the CRUD concept to a peer by comparing it to managing a physical filing cabinet—adding, viewing, editing, and removing files.",
//     "question", "How do you prioritize tasks when working on multiple projects like your Banking and Resume systems?",
//     "intention", "To check time management and organizational skills.",
//     "answer", "I use a modular approach, breaking projects into small milestones. I prioritize core functionality like security and database schemas before moving to UI enhancements." 
//   ],
//   "skillGaps": [
//     "skill", "State Management Libraries (Redux/Zustand)",
//     "severity", "medium",
//     "skill", "Unit Testing (Jest/Mocha)",
//     "severity", "high",
//     "skill", "Cloud Deployment (AWS/Azure/Vercel)",
//     "severity", "medium",
//     "skill", "Advanced CSS Frameworks (Tailwind CSS)",
//     "severity", "low"
//   ],
//   "preparationPlan": [
//     "day", 1,
//     "focus", "JavaScript & Node.js Fundamentals",
//     "tasks", "Review Event Loop, Promises, and Async/Await. Practice building a custom middleware in Express.",
//     "day", 2,
//     "focus", "React.js Deep Dive",
//     "tasks", "Study React Hooks (useMemo, useCallback) and practice implementing Context API for global state.",
//     "day", 3,
//     "focus", "Database & Security",
//     "tasks", "Review MongoDB indexing and aggregation pipelines. Practice implementing Refresh Tokens in JWT authentication.",
//     "day", 4,
//     "focus", "System Design & Testing",
//     "tasks", "Learn basic Unit Testing with Jest. Study RESTful API best practices and status codes.",
//     "day", 5,
//     "focus", "Project Walkthrough & Soft Skills",
//     "tasks", "Prepare detailed explanations for all resume projects. Conduct a mock interview focusing on behavioral questions."
//   ]
// }